name: arrowmech_e_r_p
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  map_location_picker: ^1.0.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluttertoast: 8.0.9
  intl: 0.17.0
  flutter_close_app: 1.0.0
  dropdown_button2: 1.8.2
  month_year_picker: 0.2.0+2
  video_player: 2.4.7
  chewie: 1.3.5
  shared_preferences: 2.0.15
  http: 0.13.5
  email_validator: 2.1.17
  outline_search_bar: 2.3.0
  flutter_html: 2.2.1
  double_back_to_close_app: 2.1.0
  flutter_speed_dial: 6.0.0
  swipe: 0.0.1
  simple_gesture_detector: 0.2.0
  liquid_swipe: 3.0.0
  flutter_swipe_action_cell: 3.0.4
  flutter_typeahead: 4.1.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  velocity_x: ^3.6.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  fonts: 
    - family: OutFit
      fonts: 
        - asset: assets/Fonts/OutFit/Outfit-Regular.ttf
    - family: OutFitBold
      fonts: 
        - asset: assets/Fonts/OutFit/Outfit-Bold.ttf
    - family: OutFitMedium
      fonts: 
        - asset: assets/Fonts/OutFit/Outfit-Medium.ttf
  uses-material-design: true

